export const POKEMON_TYPES = [
  { name: 'fighting', label: 'FIGHTING', color: '#C03028' },
  { name: 'psychic', label: 'PSYCHIC', color: '#F85888' },
  { name: 'poison', label: 'POISON', color: '#A040A0' },
  { name: 'dragon', label: 'DRAGON', color: '#7038F8' },
  { name: 'ghost', label: 'GHOST', color: '#705898' },
  { name: 'dark', label: 'DARK', color: '#705848' },
  { name: 'ground', label: 'GROUND', color: '#E0C068' },
  { name: 'fire', label: 'FIRE', color: '#F08030' },
  { name: 'fairy', label: 'FAIRY', color: '#EE99AC' },
  { name: 'water', label: 'WATER', color: '#6890F0' },
  { name: 'flying', label: 'FLYING', color: '#A890F0' },
  { name: 'normal', label: 'NORMAL', color: '#A8A878' },
  { name: 'rock', label: 'ROCK', color: '#B8A038' },
  { name: 'electric', label: 'ELECTRIC', color: '#F8D030' },
  { name: 'bug', label: 'BUG', color: '#A8B820' },
  { name: 'grass', label: 'GRASS', color: '#78C850' },
  { name: 'ice', label: 'ICE', color: '#98D8D8' },
  { name: 'steel', label: 'STEEL', color: '#B8B8D0' },
];
